sudo: required
addons:
  chrome: stable
    
language: node_js
node_js:
  - "8"
  
python:
  - 2.6
  - 2.7
# - 3.3
  
services:
  - docker
  - postgresql

before_script:
  - cd src/vm-angular 
  - npm install -g @angular/cli
  - npm install
  - npm install --save-dev @angular-devkit/build-angular
  - mkdir dist
  - cd dist
  - ng build --prod --aot 
  - cd ../../
  - echo "$DOCKERPASSWORD" | docker login -u "$DOCKERUSERNAME" --password-stdin
  - docker-compose build
  #- docker-compose up
  
script:
  #- ng test --watch=false --browsers=ChromeHeadless
  - docker push virtualmystery/vm-angular:aws
  - docker push virtualmystery/vm-django:aws
  - docker push virtualmystery/vm-proxy:aws

  
  
